<?php
/**
 *
 * @author  Nerijus Eimanavičius <nerijus@eimanavicius.lt>
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml">
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <base href="http://www.dg37.com.au"/>

    <meta name='Keywords' content='dg37.com.au'/>
    <meta name='Description' content='dg37.com.au'/>
    <title>Stockists dg37.com.au</title>
    <link rel="shortcut icon" href="//static.shop033.com/resources/14/162836/picture/AD/84019117.ico"/>

    <link href="/css/all?v=0xyqjPKSMwqrNBGo5PLDqEhdI8OenMJjSo3eJ-SAS801" rel="stylesheet"/>

    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <script src="/js/all?v=xlWjL1AGtpmVJ5dTMHb4QUwQYyBvZS-lyuoBld_vlDU1"></script>

    <script type="text/javascript">
        function GALink(destinationUrl) {
            document.location.href = destinationUrl;
        }
    </script>

</head>
<body>
<div id="pnlMain" class="MainOut CustomPages">
<div id="divHeaderOutside">
</div>
<div class="MainIn">
<table class="Main" width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<div id="divHeader">


<div class="HeaderSectionOut">
<div class="HeaderSectionIn">
<table class="HeaderSection" style="width:100%;" cellpadding="0" cellspacing="0">
<tr style="vertical-align: top;" class="verticalWidgetContainer">
<td>

<div class="w-1 HeaderSectionWidget ">
    <div class="RichText ">
        <div class="wWrapperOut">
            <div class="wWrapperIn">
                <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                    <tr>
                        <td>
                            <div class="wCenterOut">
                                <div class="wCenterIn">
                                    <div class="wCenter">


                                        <a href="http://www.dg37.com.au"><img alt=""
                                                                              src="//static.shop033.com/resources/14/162836/Image/DG37_web_logo.jpg"
                                                                              style="width: 163px; height: 147px;"/></a>

                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="Section1Out">
    <div class="Section1In">
        <table class="Section1" style="width:100%;" cellpadding="0" cellspacing="0">
            <tr style="vertical-align: top;" class="horizontalWidgetContainer">
                <td>

                    <div class="w42 Section1Widget Widget">
                        <div class="CustomMenu NotRichTextWidget">
                            <div class="wWrapperOut">
                                <div class="wWrapperIn">
                                    <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                                        <tbody>
                                        <tr>
                                            <td>
                                                <div class="wCenterOut">
                                                    <div class="wCenterIn">
                                                        <div class="wCenter">

                                                            <div id="236534_pnlItems"
                                                                 style="z-index: 5000; position: relative">
                                                                <ul class="dropdown dropdown-horizontal">

                                                                    <li class="first"><a href="http://www.dg37.com.au/">Home</a>
                                                                    </li>

                                                                    <li class=""><a
                                                                            href="javascript:GALink(&#39;http://www.dg37.com.au/Member/&#39;)">Login/My
                                                                            Account</a>
                                                                    </li>

                                                                    <li class=""><a
                                                                            href="http://www.dg37.com.au/Basket/">My
                                                                            Cart</a>
                                                                    </li>

                                                                    <li class=" last"><a
                                                                            href="javascript:AddToFav(&#39;http://www.dg37.com.au/&#39;, &#39;dg37.shop033.com&#39;);">Add
                                                                            to Favorites</a>
                                                                    </li>
                                                                </ul>
                                                                <br class="clr"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>


                </td>
                <td>

                    <div class="w52 Section1Widget Widget">
                        <div class="RichText ">
                            <div class="wWrapperOut">
                                <div class="wWrapperIn">
                                    <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                                        <tbody>
                                        <tr>
                                            <td>
                                                <div class="wCenterOut">
                                                    <div class="wCenterIn">
                                                        <div class="wCenter">


                                                            <script type="text/javascript">
                                                                WebFontConfig = {
                                                                    google: { families: [ 'Signika+Negative::latin' ] }
                                                                };
                                                                (function () {
                                                                    var wf = document.createElement('script');
                                                                    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                                                                        '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
                                                                    wf.type = 'text/javascript';
                                                                    wf.async = 'true';
                                                                    var s = document.getElementsByTagName('script')[0];
                                                                    s.parentNode.insertBefore(wf, s);
                                                                })(); </script>

                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>


                </td>
                <td>

                    <div class="w57 Section1Widget Widget">
                        <div class="ShoppingCart NotRichTextWidget">
                            <div class="wWrapperOut">
                                <div class="wWrapperIn">
                                    <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                                        <tbody>
                                        <tr>
                                            <td>
                                                <div class="wCenterOut">
                                                    <div class="wCenterIn">
                                                        <div class="wCenter">

                                                            <div class="MainShoppingCart" id="div_MainShoppingCart">
                                                                <div id="div_ShoppingCart" class="ShoppingCartDiv">
                                                                    <div runat="server"
                                                                         id="div_ShoppingCartBasketMessage">
                                                                        Your basket is empty
                                                                    </div>

                                                                </div>
                                                                <div style="display: none;">
                                                                    <div id='div_NotificationTemplate'
                                                                         style="overflow: auto;">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>


                </td>
            </tr>
        </table>
    </div>
</div>


<div class="Section2Out">
    <div class="Section2In">
        <table class="Section2" style="width:100%;" cellpadding="0" cellspacing="0">
            <tr style="vertical-align: top;" class="verticalWidgetContainer">
                <td>

                    <div class="w58 Section2Widget Widget">
                        <div class="CustomMenu NotRichTextWidget">
                            <div class="wWrapperOut">
                                <div class="wWrapperIn">
                                    <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                                        <tbody>
                                        <tr>
                                            <td>
                                                <div class="wCenterOut">
                                                    <div class="wCenterIn">
                                                        <div class="wCenter">

                                                            <div id="245932_pnlItems"
                                                                 style="z-index: 5000; position: relative">
                                                                <ul class="dropdown dropdown-horizontal">

                                                                    <li class="first"><a
                                                                            href="http://www.dg37.com.au/g/1231263/wholesale-access.html">Wholesale
                                                                            Access</a>
                                                                    </li>

                                                                    <li class=""><a
                                                                            href="http://www.dg37.com.au/g/1231265/about-us.html">About
                                                                            Us</a>
                                                                    </li>

                                                                    <li class=""><a
                                                                            href="http://www.dg37.com.au/g/1231264/contact.html">Contact</a>
                                                                    </li>

                                                                    <li class=" last"><a
                                                                            href="http://www.dg37.com.au/g/1240863/stockists.html">Stockists</a>
                                                                    </li>
                                                                </ul>
                                                                <br class="clr"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>


                </td>
            </tr>
        </table>
    </div>
</div>
</td>
</tr>
</table>
</div>
</div>

</div>

<table id="tblMain" cellspacing="0" cellpadding="0" border="0" runat="server" style="width: 100%; min-height: 400px;">
<tr>
<td valign="top" id="tdLeft" class="LeftColumn">


    <div class="LeftSectionOut">
        <div class="LeftSectionIn">
            <table class="LeftSection" style="width:100%;" cellpadding="0" cellspacing="0">
                <tr style="vertical-align: top;" class="verticalWidgetContainer">
                    <td><?php echo $leftSidebar; ?></td>
                </tr>
            </table>
        </div>
    </div>

</td>
<td valign="top" id="tdMiddle" class="CenterColumn">
<div class="CenterColumnContainer">

<table id="tblMiddle" style="width: 100%;" cellspacing="0" cellpadding="0" border="0">
<tr>
<td id="tdCenter">
<div class="CenterSectionOut">
<div class="CenterSectionIn">
<table class="CenterSection" style="width: 100%;" cellpadding="0" cellspacing="0">
<tr style="vertical-align: top;" class="verticalWidgetContainer">
<td>


<div class="w10 CenterSectionWidget ">
<div class="CustomPage ">
<div class="wWrapperOut">
<div class="wWrapperIn">
<table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
<tbody>
<tr>
<td>
<div class="wCenterOut">
<div class="wCenterIn">
<div class="wCenter">

<div class="CustomPageTitle">Stockists</div>
<div class="CustomPageBody"><?php echo $content; ?></div>
</div>
</div>
</div>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>

</td>
</tr>
</table>
</div>
</div>
</td>
</tr>
</table>
</div>
</td>
</tr>
</table>
<div id="divFooter">


    <div class="FooterSectionOut">
        <div class="FooterSectionIn">
            <table class="FooterSection" style="width:100%;" cellpadding="0" cellspacing="0">
                <tr style="vertical-align: top;" class="verticalWidgetContainer">
                    <td>

                        <div class="w-2 FooterSectionWidget ">
                            <div class="RichText ">
                                <div class="wWrapperOut">
                                    <div class="wWrapperIn">
                                        <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                                            <tbody>
                                            <tr>
                                                <td>
                                                    <div class="wCenterOut">
                                                        <div class="wCenterIn">
                                                            <div class="wCenter">

                                                                <div class="footerBottom">
                                                                    <div class="footerLink">
                                                                        <h4>
                                                                            <span id="cke_bm_309S"
                                                                                  style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_310S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_311S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_312S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_313S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_314S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_315S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_316S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_317S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_318S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_319S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_320S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_321S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_322S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_323S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_324S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_325S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_326S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_327S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_328S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_329S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_330S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_331S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_332S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_333S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_334S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_335S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_340S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_341S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_365S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_366S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_367S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_368S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_369S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_370S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_371S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_379S" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_380S" style="display: none;">&nbsp;</span>Terms
                                                                            &amp; Conditions<span id="cke_bm_380E"
                                                                                                  style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_379E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_371E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_370E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_369E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_368E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_367E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_366E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_365E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_341E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_340E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_335E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_334E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_333E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_332E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_331E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_330E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_329E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_328E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_327E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_326E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_325E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_324E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_323E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_322E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_321E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_320E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_319E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_318E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_317E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_316E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_315E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_314E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_313E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_312E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_311E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_310E" style="display: none;">&nbsp;</span><span
                                                                                id="cke_bm_309E" style="display: none;">&nbsp;</span>
                                                                        </h4>
                                                                        <ul>
                                                                            <li>
                                                                                <a href="/g/1241217/terms-conditions.html">Minimum
                                                                                    Order Values</a></li>
                                                                            <li>
                                                                                <a href="/g/1241217/terms-conditions.html">Freight
                                                                                    Charge Policy</a></li>
                                                                            <li>
                                                                                <a href="/g/1241217/terms-conditions.html">30
                                                                                    Day Accounts</a></li>
                                                                            <li>
                                                                                <a href="/g/1241217/terms-conditions.html">Delivery
                                                                                    Time Frames</a></li>
                                                                        </ul>
                                                                    </div>
                                                                    <div class="footerLink">
                                                                        &nbsp;</div>
                                                                    <div class="footerCopyright">
                                                                        <p>
                                                                            &copy; 2013 DG37 Pty Ltd. All rights
                                                                            reserved.<br/>
                                                                            ABN 71 318 332 914<br/>
                                                                            <span
                                                                                style="font-family:arial,helvetica,sans-serif;"><span
                                                                                    style="font-size:16px;">Phone: 02 9771 5454</span></span><br/>
                                                                            <a href="/g/1241216/privacy-policy.html">Privacy
                                                                                Policy</a></p>

                                                                        <div style="text-align: right;">
                                                                            &nbsp;</div>
                                                                    </div>
                                                                </div>
                                                                <br/>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </td>
                </tr>
            </table>
        </div>
    </div>

</div>
</td>
</tr>
</table>
</div>
<div id="divFooterOutside">
</div>
<div id="lc">
    <div class="AshopLinkItem" style="background-color: transparent !important;">
        <p style="text-align: center;"><a href="http://www.ashop.com.au" target="_blank">Ecommerce Software by Ashop</a>
        </p>
    </div>
</div>

</div>

</body>
</html>