<?php
/**
 *
 * @author  Nerijus Eimanavičius <nerijus@eimanavicius.lt>
 */
?>
<div class="w59 LeftSectionWidget Widget">
    <div class="Categories NotRichTextWidget">
        <div class="wWrapperOut">
            <div class="wWrapperIn">
                <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                    <tr>
                        <td>
                            <div class="wHeaderOut">
                                <div class="wHeaderIn">
                                    <div class="wHeader">
                                        Product
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="wCenterOut">
                                <div class="wCenterIn">
                                    <div class="wCenter">


                                        <ul class="category-list list-vertical">

                                            <li class="first"><a
                                                    href="http://www.dg37.com.au/c/4495640/1/bedding.html">Bedding</a>


                                            </li>


                                            <li class=""><a
                                                    href="http://www.dg37.com.au/c/4495156/1/cushions.html">Cushions</a>


                                            </li>


                                            <li class=""><a
                                                    href="http://www.dg37.com.au/c/4495158/1/throws.html">Throws</a>


                                            </li>


                                            <li class=""><a
                                                    href="http://www.dg37.com.au/c/4495160/1/decor.html">Decor</a>


                                            </li>


                                            <li class=" last"><a
                                                    href="http://www.dg37.com.au/c/4495159/1/on-sale.html">On
                                                    Sale</a>


                                            </li>

                                        </ul>

                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="w68 LeftSectionWidget Widget">
    <div class="Search NotRichTextWidget">
        <div class="wWrapperOut">
            <div class="wWrapperIn">
                <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                    <tr>
                        <td>
                            <div class="wHeaderOut">
                                <div class="wHeaderIn">
                                    <div class="wHeader">
                                        Search
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="wCenterOut">
                                <div class="wCenterIn">
                                    <div class="wCenter">


                                        <form id="04759acf-6a22-4a9c-9d8b-b7b1d928dd82"
                                              action="http://www.dg37.com.au/Listing/search"
                                              method="GET">
                                            <div id="divCenter">
                                                <center>
                                                    <table>
                                                        <tbody>
                                                        <tr>
                                                            <td>
                                                                <input type="text"
                                                                       id="txtSearch"
                                                                       name="keywords"
                                                                       class="wTextField default-value"
                                                                       style="width: 100%;"
                                                                       value="Search..."
                                                                       size="16"/><input
                                                                    type="hidden"
                                                                    name="searchType"
                                                                    value="2"/><input
                                                                    type="hidden"
                                                                    name="sortItem" value="7"/>
                                                            </td>
                                                            <td>
                                                                <a id="btnSearch"
                                                                   class="wButton wButtonSmall"
                                                                   onclick=""
                                                                   href="javascript:$('#04759acf-6a22-4a9c-9d8b-b7b1d928dd82').submit()">Search</a>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                    <div class="advanced-search-text">
                                                        <a href='http://www.dg37.com.au/Listing/search'>
                                                            Advanced Search</a></div>
                                                </center>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>