<?php
/**
 *
 * @author  Nerijus Eimanavičius <nerijus@eimanavicius.lt>
 */
?>

<div class="w68 w59 LeftSectionWidget Widget">
    <div class="Search Categories NotRichTextWidget">
        <div class="wWrapperOut">
            <div class="wWrapperIn">
                <table class="wWrapper" width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                    <tr>
                        <td>
                            <div class="wHeaderOut">
                                <div class="wHeaderIn">
                                    <div class="wHeader">
                                        Store Locator.
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="wCenterOut">
                                <div class="wCenterIn">
                                    <div class="wCenter">

                                            <div id="divCenter">
                                                <center>
                                                    <table>
                                                        <tbody>
                                                        <tr>
                                                            <td>
                                                                <input type="text"
                                                                       id="txtSearch"
                                                                       name="keywords"
                                                                       class="wTextField default-value"
                                                                       style="width: 100%;"
                                                                       value="Enter Location"
                                                                       size="16"/><input
                                                                    type="hidden"
                                                                    name="searchType"
                                                                    value="2"/><input
                                                                    type="hidden"
                                                                    name="sortItem" value="7"/>
                                                            </td>
                                                            <td>
                                                                <a id="btnSearch"
                                                                   class="wButton wButtonSmall"
                                                                   href="javascript:void(0);">Search</a>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </center>
                                            </div>

<br/>
<br/>
                                        <ul class="category-list list-vertical">
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

